# Generated by Django 5.0.4 on 2024-11-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=60, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_time', models.CharField(blank=True, max_length=10, null=True)),
                ('event_duration', models.FloatField(blank=True, max_length=10, null=True)),
                ('event_location', models.CharField(blank=True, max_length=60, null=True)),
                ('event_category', models.CharField(blank=True, max_length=60, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('event_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
