# Generated by Django 5.0.4 on 2024-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
