# Generated by Django 5.0.4 on 2024-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
