# Generated by Django 5.0.4 on 2024-11-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_security_question_user_security_question_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgetPasswordModel',
        ),
    ]
