# Generated by Django 5.0.4 on 2024-11-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_to_all_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
